QUESTION 1

#include <iostream>
using namespace std;

int main() {

    string name, id; 

    cout<<"What is your name?"<<endl;
    cin>>name;
    cout<<"Hello " + name + "."<<endl;
    cout<<"What is your student ID?"<<endl;
    cin>>id;
    cout<<"Your ID is " + id + "."<<endl; 

    return 0;
}




QUESTION 2

#include <iostream>
using namespace std;

int main() {

    int var1;
    int var2;
    
    cout<< "Please enter first value: ";
    cin>> var1;
    cout<< "Please enter second value: ";
    cin>> var2;
    
    int sum = var1 + var2;
    int diff = var1 - var2;
    int prod = var1 * var2;
    
    cout<<"Value 1: "<<var1<<endl; 
    cout<<"Value 2: "<<var2<<endl;
    
    cout<<"Summation: "<<sum<<endl;
    cout<<"Difference: "<<diff<<endl;
    cout<<"Production: "<<prod<<endl;
}




QUESTION 3


